### ISSUE TITLE
Espressif-IDE 2.7.0 always download crosstool-NG release file from github

### ISSUE THREAD

**Issue by mzhboy** [espressif/idf-installer#160]
**Describe the bug**
unselect [Chip Targets] of [esp32-c3] when installing Espressif-IDE 2.7.0, installer always download [riscv32-esp-elf-gcc8_4_0-esp-2021r2-patch5-win64.zip]( https://github.com/espressif/crosstool-NG/releases/download/esp-2021r2-patch5/riscv32-esp-elf-gcc8_4_0-esp-2021r2-patch5-win64.zip) from github, while installer does not have proxy setting so it's extreme slow download process and usually ends installation fail because of gfw.

**To Reproduce**
1. Living in mainland China
2. fresh install Espressif-IDE 2.7.0
3. default settings except unselect install support for esp32-c3
4. continue installation, you installation process will be stuck.

**Expected behavior**
slow download from github and ends with failed installation

**Screenshots**
![Snipaste](https://user-images.githubusercontent.com/5281193/210249248-b8fbebf4-627e-46f5-8437-2c989eeb09be.jpg)

![Snipaste_](https://user-images.githubusercontent.com/5281193/210248454-d4c59459-3f2a-4109-8575-076db8ee9b13.jpg)

**Comment by igrr** [comment]
This is probably because we also [require](https://github.com/espressif/esp-idf/blob/0025915dc489a9d45f99aed74920346f8ac4ec09/tools/tools.json#L453-L454) riscv32-esp-elf-gcc for ESP32-S2 and ESP32-S3 (due to their RISC-V ULP coprocessors), but the installer currently [doesn't install](https://github.com/espressif/idf-installer/blob/8c88b18e528ec3b4d2898cdaecad918aaa4bf5b6/src/InnoSetup/IdfToolsSetup.iss#L241-L254) `riscv32-esp-elf` tool for ESP32-S2 and ESP32-S3.

(This was also mentioned in https://github.com/espressif/idf-installer/pull/158#discussion_r1055237061.)

**Comment by mzhboy** [comment]
anyway, I manage finish install ESP-IDE by 
 1. download `xpack-riscv-none-elf-gcc-12.2.0-1-win32-x64.zip` and put it into `Espressif\dist\`
 2. select [esp32-c3] (basically leave everything default)

I don't konw which option works, but it worked.

**Comment by mzhboy** [comment]
I  highly suggest download extra package from espressif.com or make `offline installer` truly `offline`, we don't really mind a bigger installer package.

**Comment by georgik** [comment]
@mzhboy There are updated installers available:
- https://github.com/espressif/idf-installer/releases/tag/espressif-ide-2.7.0-esp-idf-4.4.3
- https://github.com/espressif/idf-installer/releases/tag/espressif-ide-2.7.0-esp-idf-5.0

Please test the installation.
